name: Build-Docker-Image

on: [push]

jobs:
  build_docker_img:
     runs-on: ubuntu-latest
     env:
       TAG: python-api
       DOCKER_USERNAME: ambarish6
       DOCKER_PASSWORD: Ambi@9380
       USER: ambarish6
       VERSION: latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v1
       
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ env.DOCKER_USERNAME }}
         password: ${{ env.DOCKER_PASSWORD }}
       
     - name: Build Docker image
       run: docker build -t ${{ env.USER }}/$TAG:${{ env.VERSION }} .
      
     - name: Push Docker image to Docker Hub
       run: docker push ${{ env.USER }}/$TAG:${{ env.VERSION }}
       
     - name: Image Scan
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: 'docker://${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          
    #  - name: Upload the scan result to GitHub Security
    #    uses: github/codeql-action/upload-sarif@v2
    #    with:
    #       sarif_file: 'trivy-image-results.sarif'
    #       category: 'image'
