name: Build-Docker-Image-Parent

on: [push]

jobs:
  build_docker_img:
    runs-on: ubuntu-latest
    env:
      TAG: python-api
      DOCKER_USERNAME: ambarish6
      DOCKER_PASSWORD: Ambi@9380
      USER: ambarish6
      VERSION: latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build Docker image
      id: build_image
      run: docker build -t ${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }} .

    - name: Trigger Child Workflow
      if: ${{ always() }}
      uses: ./.github/workflows/child_workflow.yml
      with:
        image_tag: ${{ steps.build_image.outputs.image_tag }}
