name: Parent Workflow
on:
  workflow_dispatch:
jobs:
  trigger_and_monitor_child_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child Workflow
        id: trigger_child
        uses: actions/github-script@v4
        with:
          script: |
            const { data: { id: workflow_id } } = await github.actions.createWorkflowDispatch({
              owner: 'ambarih', // Change to your repository owner
              repo: 'child_work', // Change to your repository name
              workflow_file: 'child_workflow.yaml', // Name of the child workflow file
              ref: 'main', // Branch where the workflow is located
              inputs: {
                trigger_child_workflow: 'true' // Pass any necessary inputs to the child workflow
              }
            });
            console.log(`Child workflow triggered with ID: ${workflow_id}`);

      - name: Wait for Child Workflow Completion
        id: wait_child_workflow
        if: steps.trigger_child.outputs.workflow_id != null
        run: |
          status="queued"
          while [[ $status == "queued" || $status == "in_progress" ]]; do
            sleep 500
            status=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/ambarih/trivy_new/actions/runs/${{ steps.trigger_child.outputs.workflow_id }} | jq -r .status)
          done
          if [[ $status != "completed" ]]; then
            echo "Child workflow failed or canceled"
            exit 1
          fi
          echo "Child workflow completed successfully"

      - name: Remaining Parent Workflow Steps
        if: steps.wait_child_workflow.outputs.status == 'completed'
        run: |
          echo "Continuing with remaining steps after child workflow completion"
