name: Parent Workflow
on:
  push:
    branches:
      - main
jobs:
  trigger_child_workflow:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ambarih
      REPO_NAME: child_work
      CHILD_WORKFLOW_ID: 95072086
      token: ${{ secrets.token }}
    steps:
      - name: Trigger Child Workflow
        uses: actions/checkout@v2
      - name: Run Child Workflow
        run: |
          response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$CHILD_WORKFLOW_ID/dispatches -d '{"ref":"main"}' -w "%{http_code}")
          if [[ $response != 2* ]]; then
            echo "Failed to trigger child workflow"
            exit 1
          fi
      - name: Wait for Child Workflow Completion
        id: wait_child_workflow
        run: |
          status="queued"
          while [[ $status == "queued" || $status == "in_progress" ]]; do
            sleep 30
            status=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$CHILD_WORKFLOW_ID/runs/latest | jq -r .status)
          done
          if [[ $status != "completed" ]]; then
            echo "Child workflow failed or canceled"
            exit 1
          fi
      - name: Remaining Parent Workflow Steps
        if: steps.wait_child_workflow.outputs.status == 'completed'
        run: |
          echo "Child workflow completed successfully, continuing with remaining steps"
