# .github/workflows/parent_workflow.yml
name: Parent Workflow
on:
  push:
    branches:
      - main
jobs:
  trigger_child_workflow:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: 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
      REPO_OWNER: ambarih
      REPO_NAME: trivy_new
      CHILD_WORKFLOW_ID: 95072086
    steps:
      - name: Trigger Child Workflow
        uses: actions/checkout@v2
      - name: Run Child Workflow
        run: |
          response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$CHILD_WORKFLOW_ID/dispatches -d '{"ref":"main"}' -w "%{http_code}")
          if [[ $response != 2* ]]; then
            echo "Failed to trigger child workflow"
            exit 1
          fi
      - name: Example 
        run: echo "This is an example step in the parent workflow"